rootProject.name = "echo"
include(":backend:dashboard")
include(":backend:dashboard-security-api")
include(":backend:dashboard-security-basic")
include(":backend:dashboard-security-ldap")
include(":backend:configuration")
include(":backend:integration-ldap")
include(":backend:storage-jpa")
include(":backend:organization-api")
include(":backend:synchronization-manager")
