sonarqube:
  url: http://sonarqube.consdata.local
  username: sonar
#  password:
app:
  layoutConfiguration: classpath:layoutConfiguration.json
  syncDelay: 600000
  keystore:
    file: file:sonarqube-keystore.keystore
    password: q1w2e3r4