module.exports = {
  projects: [
    '<rootDir>/apps/sonarqube-companion',
    '<rootDir>/libs/overview',
    '<rootDir>/libs/ui-components/sidebar',
    '<rootDir>/libs/ui-components/groups-tree',
    '<rootDir>/libs/ui-components/group-overview',
    '<rootDir>/libs/ui-components/value-badge',
    '<rootDir>/libs/ui-components/timeline',
    '<rootDir>/libs/ui-components/heatmap',
    '<rootDir>/libs/group',
    '<rootDir>/libs/sidenav',
    '<rootDir>/libs/ui-components/side-groups-tree',
    '<rootDir>/libs/ui-components/table',
    '<rootDir>/libs/project',
    '<rootDir>/libs/member',
    '<rootDir>/libs/ui-components/select',
    '<rootDir>/libs/settings',
  ],
};
