#!/bin/bash

# verify node
command -v node >/dev/null 2>&1 || {
    echo "Missing node, pleas install node in version at least 0.10.0"
    exit 1
}

# verify grunt npm module installed
if [ ! -d  node_modules/tsd ]; then
    echo "Missing grunt node module installed, please run npm update first"
    exit 1
fi

# run bower
./node_modules/tsd/build/cli.js $@
